// Code generated by qtc from "sql2_xorm_model.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/sql2_xorm_model.qtpl:1
package templates

//line templates/sql2_xorm_model.qtpl:1
import (
	"github.com/xvpenghao/sql2struct/model"
	"strings"
)

// 结构体的生成

//line templates/sql2_xorm_model.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/sql2_xorm_model.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/sql2_xorm_model.qtpl:7
func StreamGenerateModelFile(qw422016 *qt422016.Writer, sql *model.CreateTableSql, structName, pkg string) {
//line templates/sql2_xorm_model.qtpl:7
	qw422016.N().S(`
package `)
//line templates/sql2_xorm_model.qtpl:8
	qw422016.E().S(pkg)
//line templates/sql2_xorm_model.qtpl:8
	qw422016.N().S(`

import (
    "time"
)

type `)
//line templates/sql2_xorm_model.qtpl:14
	qw422016.E().S(structName)
//line templates/sql2_xorm_model.qtpl:14
	qw422016.N().S(` struct {
`)
//line templates/sql2_xorm_model.qtpl:16
	for _, c := range sql.ColumnList {
//line templates/sql2_xorm_model.qtpl:18
		name := strings.Title(c.Name)
		nameLower := strings.ToLower(c.Name)

//line templates/sql2_xorm_model.qtpl:22
		qw422016.E().S(name)
//line templates/sql2_xorm_model.qtpl:22
		qw422016.N().S(` `)
//line templates/sql2_xorm_model.qtpl:23
		qw422016.E().S(c.DataType)
//line templates/sql2_xorm_model.qtpl:23
		qw422016.N().S(` `)
//line templates/sql2_xorm_model.qtpl:23
		qw422016.N().S(``)
//line templates/sql2_xorm_model.qtpl:23
		qw422016.N().S("`")
//line templates/sql2_xorm_model.qtpl:23
		qw422016.N().S(`zh:"`)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.E().S(c.Comment)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.N().S(`" json:"`)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.E().S(c.Name)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.N().S(`" form:"`)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.E().S(c.Name)
//line templates/sql2_xorm_model.qtpl:24
		qw422016.N().S(`"`)
//line templates/sql2_xorm_model.qtpl:25
		if nameLower == "id" {
//line templates/sql2_xorm_model.qtpl:26
			qw422016.N().S(` `)
//line templates/sql2_xorm_model.qtpl:26
			qw422016.N().S(`xorm:"'id' bigint pk autoincr"`)
//line templates/sql2_xorm_model.qtpl:27
		}
//line templates/sql2_xorm_model.qtpl:27
		qw422016.N().S(``)
//line templates/sql2_xorm_model.qtpl:27
		qw422016.N().S("`")
//line templates/sql2_xorm_model.qtpl:28
		qw422016.N().S(`
`)
//line templates/sql2_xorm_model.qtpl:29
	}
//line templates/sql2_xorm_model.qtpl:30
	qw422016.N().S(`
}

    `)
//line templates/sql2_xorm_model.qtpl:33
	streamgenerateTableNameMethod(qw422016, sql.TableName, structName)
//line templates/sql2_xorm_model.qtpl:33
	qw422016.N().S(`
    `)
//line templates/sql2_xorm_model.qtpl:34
	streamgenerateBeforeInsertMethod(qw422016, structName)
//line templates/sql2_xorm_model.qtpl:34
	qw422016.N().S(`
    `)
//line templates/sql2_xorm_model.qtpl:35
	streamgenerateBeforeUpdateMethod(qw422016, structName)
//line templates/sql2_xorm_model.qtpl:35
	qw422016.N().S(`
`)
//line templates/sql2_xorm_model.qtpl:36
}

//line templates/sql2_xorm_model.qtpl:36
func WriteGenerateModelFile(qq422016 qtio422016.Writer, sql *model.CreateTableSql, structName, pkg string) {
//line templates/sql2_xorm_model.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/sql2_xorm_model.qtpl:36
	StreamGenerateModelFile(qw422016, sql, structName, pkg)
//line templates/sql2_xorm_model.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line templates/sql2_xorm_model.qtpl:36
}

//line templates/sql2_xorm_model.qtpl:36
func GenerateModelFile(sql *model.CreateTableSql, structName, pkg string) string {
//line templates/sql2_xorm_model.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/sql2_xorm_model.qtpl:36
	WriteGenerateModelFile(qb422016, sql, structName, pkg)
//line templates/sql2_xorm_model.qtpl:36
	qs422016 := string(qb422016.B)
//line templates/sql2_xorm_model.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/sql2_xorm_model.qtpl:36
	return qs422016
//line templates/sql2_xorm_model.qtpl:36
}

// TableName

//line templates/sql2_xorm_model.qtpl:40
func streamgenerateTableNameMethod(qw422016 *qt422016.Writer, tableName, structName string) {
//line templates/sql2_xorm_model.qtpl:40
	qw422016.N().S(`
    func (this *`)
//line templates/sql2_xorm_model.qtpl:41
	qw422016.E().S(structName)
//line templates/sql2_xorm_model.qtpl:41
	qw422016.N().S(`) TableName() string {
        return "`)
//line templates/sql2_xorm_model.qtpl:42
	qw422016.E().S(tableName)
//line templates/sql2_xorm_model.qtpl:42
	qw422016.N().S(`"
    }
`)
//line templates/sql2_xorm_model.qtpl:44
}

//line templates/sql2_xorm_model.qtpl:44
func writegenerateTableNameMethod(qq422016 qtio422016.Writer, tableName, structName string) {
//line templates/sql2_xorm_model.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/sql2_xorm_model.qtpl:44
	streamgenerateTableNameMethod(qw422016, tableName, structName)
//line templates/sql2_xorm_model.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line templates/sql2_xorm_model.qtpl:44
}

//line templates/sql2_xorm_model.qtpl:44
func generateTableNameMethod(tableName, structName string) string {
//line templates/sql2_xorm_model.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/sql2_xorm_model.qtpl:44
	writegenerateTableNameMethod(qb422016, tableName, structName)
//line templates/sql2_xorm_model.qtpl:44
	qs422016 := string(qb422016.B)
//line templates/sql2_xorm_model.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/sql2_xorm_model.qtpl:44
	return qs422016
//line templates/sql2_xorm_model.qtpl:44
}

// BeforeInsert

//line templates/sql2_xorm_model.qtpl:48
func streamgenerateBeforeInsertMethod(qw422016 *qt422016.Writer, structName string) {
//line templates/sql2_xorm_model.qtpl:48
	qw422016.N().S(`
    func (this *`)
//line templates/sql2_xorm_model.qtpl:49
	qw422016.E().S(structName)
//line templates/sql2_xorm_model.qtpl:49
	qw422016.N().S(`) BeforeInsert() {
        if this.CreateTime == "" {
            this.CreateTime = time.Now().Format("2006-01-02 15:04:05")
        }
        if this.UpdateTime == "" {
            this.UpdateTime = time.Now().Format("2006-01-02 15:04:05")
        }
    }
`)
//line templates/sql2_xorm_model.qtpl:57
}

//line templates/sql2_xorm_model.qtpl:57
func writegenerateBeforeInsertMethod(qq422016 qtio422016.Writer, structName string) {
//line templates/sql2_xorm_model.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/sql2_xorm_model.qtpl:57
	streamgenerateBeforeInsertMethod(qw422016, structName)
//line templates/sql2_xorm_model.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line templates/sql2_xorm_model.qtpl:57
}

//line templates/sql2_xorm_model.qtpl:57
func generateBeforeInsertMethod(structName string) string {
//line templates/sql2_xorm_model.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/sql2_xorm_model.qtpl:57
	writegenerateBeforeInsertMethod(qb422016, structName)
//line templates/sql2_xorm_model.qtpl:57
	qs422016 := string(qb422016.B)
//line templates/sql2_xorm_model.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/sql2_xorm_model.qtpl:57
	return qs422016
//line templates/sql2_xorm_model.qtpl:57
}

//line templates/sql2_xorm_model.qtpl:60
func streamgenerateBeforeUpdateMethod(qw422016 *qt422016.Writer, structName string) {
//line templates/sql2_xorm_model.qtpl:60
	qw422016.N().S(`
    func (this *`)
//line templates/sql2_xorm_model.qtpl:61
	qw422016.E().S(structName)
//line templates/sql2_xorm_model.qtpl:61
	qw422016.N().S(`) BeforeUpdate() {
        this.UpdateTime = time.Now().Format("2006-01-02 15:04:05")
    }
`)
//line templates/sql2_xorm_model.qtpl:64
}

//line templates/sql2_xorm_model.qtpl:64
func writegenerateBeforeUpdateMethod(qq422016 qtio422016.Writer, structName string) {
//line templates/sql2_xorm_model.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/sql2_xorm_model.qtpl:64
	streamgenerateBeforeUpdateMethod(qw422016, structName)
//line templates/sql2_xorm_model.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line templates/sql2_xorm_model.qtpl:64
}

//line templates/sql2_xorm_model.qtpl:64
func generateBeforeUpdateMethod(structName string) string {
//line templates/sql2_xorm_model.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/sql2_xorm_model.qtpl:64
	writegenerateBeforeUpdateMethod(qb422016, structName)
//line templates/sql2_xorm_model.qtpl:64
	qs422016 := string(qb422016.B)
//line templates/sql2_xorm_model.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/sql2_xorm_model.qtpl:64
	return qs422016
//line templates/sql2_xorm_model.qtpl:64
}
